### ISSUE TITLE
インストールすべきパッケージの説明が最新の実装と合っていない

### ISSUE THREAD

**Issue by ya2ha4** [TaktstockJp/yomiage_VOICEVOX_verT#3]
readmeの
- 導入が必要なソフト
- 起動方法
に沿ってセットアップし、 discordbot.py を実行すると下記のメッセージが表示されボットが動作しません。

```
Traceback (most recent call last):
  File "~\yomiage_VOICEVOX_verT\discordbot.py", line 9, in <module>
    from for_developer.discordbot_functions import *
  File "~\yomiage_VOICEVOX_verT\for_developer\discordbot_functions.py", line 14, in <module>
    from for_developer.voice_generator import VoiceVoxVoiceGenerator, AIVoiceVoiceGenerator
  File "~\yomiage_VOICEVOX_verT\for_developer\voice_generator.py", line 2, in <module>
    import clr
ModuleNotFoundError: No module named 'clr'
```

これは clr を使用する為の pyhonnet のインストール説明が抜けているため発生しています。

また、「導入が必要なソフト」の
> 3. pycord.py, PyNaClのインストール

の項目でドキュメントでは pycord.py をインストールするよう説明がありますが、
直後のプロンプトでは discord.py を github からインストールするようになっています。

A.I.VOICEによる読み上げ対応 eddb305d5e81edaceb11bf9e2be35d45754d1c30 でセットアップ方法が変わっているようですので、他箇所含めドキュメントを見直して更新して頂くことは可能でしょうか？

**Comment by TaktstockJp** [comment]
17dac17df8ad3c00e3624eedface9a2a79a806a6, 494f52661f5fb5da23470cb92f86ae38c694b383, 7bd591f3ccd133033a70c1654a156f31b753d939, 2d8e6a0d2ae613d84fd5fed9fd61d8c65ad18cd0 でドキュメントを修正しました。（コミットコメント間違えたのは見逃してください…）
また、requirements.txtを新規作成しました。

**Comment by ya2ha4** [comment]
ドキュメント更新されていることを確認致しました。
対応頂きありがとうございました！
